objects:
  user_permissions_set:
    admin: boolean
    mobile: boolean
    status_box: boolean
    reports: boolean
    manage_timesheets: boolean
    manage_authorization: boolean
    manage_users: boolean
    manage_my_timesheets: boolean
    manage_jobcodes: boolean
    approve_timesheets: boolean
  user:
    id: integer
    username: string
    email: string
    first_name: string
    last_name: string
    group_id: integer
    manager_of_group_ids: [ integer ]
    employee_number: integer
    salaried: boolean
    exempt: boolean
    payroll_id: string
    client_url: string
    mobile_number: string
    hire_date: date
    term_date: date
    last_active: datetime
    active: boolean
    require_password_change: boolean
    approved_to: date
    submitted_to: date
    last_modified: datetime
    created: datetime
    permissions: user_permissions_set
endpoints:
  users:
    url: "/users"
    object: user
    actions:
      - list
      - add
      - edit
    filters:
      ids: integer[]
      usernames: string[]
      active: boolean
      first_name: string
      last_name: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  current_user:
    url: "/current_user"
    object: user
    actions:
      - get
