objects:
  user_permissions_set:
    admin: boolean
    mobile: boolean
    status_box: boolean
    reports: boolean
    manage_timesheets: boolean
    manage_authorization: boolean
    manage_users: boolean
    manage_my_timesheets: boolean
    manage_jobcodes: boolean
    approve_timesheets: boolean
  user:
    id: integer
    username: string
    email: string
    first_name: string
    last_name: string
    group_id: integer
    manager_of_group_ids: [ integer ]
    employee_number: integer
    salaried: boolean
    exempt: boolean
    payroll_id: string
    client_url: string
    mobile_number: string
    hire_date: date
    term_date: date
    last_active: datetime
    active: boolean
    require_password_change: boolean
    approved_to: date
    submitted_to: date
    last_modified: datetime
    created: datetime
    permissions: user_permissions_set
  jobcode:
    id: integer
    parent_id: integer
    name: string
    short_code: string
    type: string
    billable: boolean
    billable_rate: float
    has_children: boolean
    assigned_to_all: boolean
    required_customfields: [ integer ]
    filtered_customfielditems: object
    active: boolean
    last_modified: datetime
    created: datetime
  timesheet_deleted:
    id: integer
    user_id: integer
    jobcode_id: integer
    start: datetime
    end: datetime
    date: date
    duration: integer
    locked: integer
    notes: string
    customfields: string
    created: datetime
    last_modified: datetime
    type: string
  timesheet:
    id: integer
    user_id: integer
    jobcode_id: integer
    locked: integer
    notes: string
    customfields: string
    created: datetime
    last_modified: datetime
    type: string
    on_the_clock: boolean
    start: datetime
    end: datetime
    date: date
    duration: integer
    tz: integer
    tz_str: string
    location: string
    __config:
      exclude:
        add:
          - id
          - locked
          - on_the_clock
          - tz
          - tz_str
          - location
        edit:
          - id
          - locked
          - on_the_clock
          - tz
          - tz_str
          - location
  jobcode_assignment:
    id: integer
    user_id: integer
    jobcode_id: integer
    active: boolean
    last_modified: datetime
    created: datetime
  custom_field:
    id: integer
    name: string
    short_code: string
    required: boolean
    applies_to: string
    type: string
    ui_preference: string
    regex_filter: string
    last_modified: datetime
    created: datetime
    required_customfields: [ integer ]
  custom_field_item:
    id: integer
    customfield_id: integer
    name: string
    short_code: string
    active: boolean
    last_modified: datetime
    created: datetime
    required_customfields: [ integer ]
  geolocation:
    id: integer
    user_id: integer
    accuracy: integer
    altitude: float
    latitude: float
    longitude: float
    speed: float
    heading: integer
    source: string
    device_identifier: string
    created: datetime
endpoints:
  geolocations:
    url: "/geolocations"
    object: geolocation
    actions:
      - list
      - add
    filters:
      ids: integer[]
      modified_before: datetime
      modified_since: datetime
      user_ids: integer[]
      group_ids: integer[]
      per_page: integer
      page: integer
  custom_field_items:
    url: "/customfielditems"
    object: custom_field_item
    actions:
      - list
      - add
      - edit
    filters:
      customfield_id: integer
      ids: integer[]
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  custom_fields:
    url: "/customfields"
    object: custom_field
    actions:
      - list
    filters:
      ids: integer[]
      applies_to: string
      value_type: string
      modified_before: string
      modified_since: string
      per_page: integer
      page: integer
  jobcodes:
    url: "/jobcodes"
    object: jobcode
    actions:
      - list
      - add
      - edit
    filters:
      ids: integer[]
      parent_ids: integer[]
      type: string
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  jobcode_assignments:
    url: "/jobcode_assignments"
    object: jobcode_assignment
    actions:
      - list
      - add
      - delete
    filters:
      user_ids: integer[]
      type: string
      jobcode_parent_id: integer
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  timesheets_deleted:
    url: "/timesheets_deleted"
    object: timesheet_deleted
    actions:
      - list
    filters:
      start_date: date
      end_date: date
      ids: integer[]
      modified_since: datetime
      modified_before: datetime
      group_ids: string
      user_ids: integer[]
      username: string
      jobcode_ids: integer[]
      jobcode_type: string
      type: string
      order_results_by: string
      order_results_reverse: boolean
      page: integer
      per_page: integer
  timesheets:
    url: "/timesheets"
    object: timesheet
    actions:
      - list
      - add
      - edit
      - delete
    filters:
      ids: integer[]
      start_date: date
      end_date: date
      jobcode_ids: integer[]
      user_ids: integer[]
      group_ids: integer[]
      on_the_clock: boolean
      jobcode_type: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  users:
    url: "/users"
    object: user
    actions:
      - list
      - add
      - edit
    filters:
      ids: integer[]
      usernames: string[]
      active: boolean
      first_name: string
      last_name: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  current_user:
    url: "/current_user"
    object: user
    actions:
      - list
