objects:
  reminder:
    id: integer
    user_id: integer
    reminder_type: string
    due_time: string
    due_days_of_week: string
    distribution_methods: [ string ]
    active: boolean
    enabled: boolean
    last_modified: datetime
    created: datetime
  payroll:
    user_id: integer
    client_id: integer
    start_date: date
    end_date: date
    total_re_seconds: integer
    total_ot_seconds: integer
    total_dt_seconds: integer
    total_pto_seconds: integer
    total_work_seconds: integer
    pto_seconds: hash
  project:
    start_date: date
    end_date: date
    totals: hash
  current_totals:
    user_id: integer
    on_the_clock: boolean
    timesheet_id: integer
    jobcode_id: integer
    group_id: integer
    shift_seconds: integer
    day_seconds: integer
  effective_settings:
    general: hash
    time_entry: hash
    invoicing: hash
    alerts: hash
    dialin: hash
    sounds: hash
  last_modified_timestamps:
    __config:
      default_field_type: datetime
  user_permissions_set:
    admin: boolean
    mobile: boolean
    status_box: boolean
    reports: boolean
    manage_timesheets: boolean
    manage_authorization: boolean
    manage_users: boolean
    manage_my_timesheets: boolean
    manage_jobcodes: boolean
    approve_timesheets: boolean
  user:
    id: integer
    username: string
    email: string
    first_name: string
    last_name: string
    group_id: integer
    manager_of_group_ids: [ integer ]
    employee_number: integer
    salaried: boolean
    exempt: boolean
    payroll_id: string
    client_url: string
    mobile_number: string
    hire_date: date
    term_date: date
    last_active: datetime
    active: boolean
    require_password_change: boolean
    approved_to: date
    submitted_to: date
    last_modified: datetime
    created: datetime
    permissions: user_permissions_set
  jobcode:
    id: integer
    parent_id: integer
    name: string
    short_code: string
    type: string
    billable: boolean
    billable_rate: float
    has_children: boolean
    assigned_to_all: boolean
    required_customfields: [ integer ]
    filtered_customfielditems: object
    active: boolean
    last_modified: datetime
    created: datetime
  timesheet_deleted:
    id: integer
    user_id: integer
    jobcode_id: integer
    start: datetime
    end: datetime
    date: date
    duration: integer
    locked: integer
    notes: string
    customfields: string
    created: datetime
    last_modified: datetime
    type: string
  timesheet:
    id: integer
    user_id: integer
    jobcode_id: integer
    locked: integer
    notes: string
    customfields: string
    created: datetime
    last_modified: datetime
    type: string
    on_the_clock: boolean
    start: datetime
    end: datetime
    date: date
    duration: integer
    tz: integer
    tz_str: string
    location: string
    __config:
      exclude:
        add:
          - id
          - locked
          - on_the_clock
          - tz
          - tz_str
          - location
        edit:
          - id
          - locked
          - on_the_clock
          - tz
          - tz_str
          - location
  jobcode_assignment:
    id: integer
    user_id: integer
    jobcode_id: integer
    active: boolean
    last_modified: datetime
    created: datetime
  custom_field:
    id: integer
    name: string
    short_code: string
    required: boolean
    applies_to: string
    type: string
    ui_preference: string
    regex_filter: string
    last_modified: datetime
    created: datetime
    required_customfields: [ integer ]
  custom_field_item:
    id: integer
    customfield_id: integer
    name: string
    short_code: string
    active: boolean
    last_modified: datetime
    created: datetime
    required_customfields: [ integer ]
  geolocation:
    id: integer
    user_id: integer
    accuracy: integer
    altitude: float
    latitude: float
    longitude: float
    speed: float
    heading: integer
    source: string
    device_identifier: string
    created: datetime
endpoints:
  reminders:
    url: "/reminders"
    object: reminder
    actions:
      - list
      - add
      - edit
    filters:
      user_ids: integer[]
      reminder_types: string[]
      modified_since: datetime
  project:
    url: "/reports/project"
    object: project
    actions:
      - report
    filters:
      start_date: date
      end_date: date
      user_ids: integer[]
      group_ids: integer[]
      jobcode_ids: integer[]
      jobcode_type: string
      customfielditems: hash
  payroll:
    url: "/reports/payroll"
    object: payroll
    actions:
      - report
    filters:
      start_date: date
      end_date: date
      user_ids: integer
      group_ids: integer
      include_zero_time: string
  current_totals:
    url: "/reports/current_totals"
    object: current_totals
    actions:
      - report
    filters:
      user_ids: integer[]
      group_ids: integer[]
      on_the_clock: string
      page: integer
      per_page: integer
      order_by: string
      order_desc: boolean
  last_modified_timestamps:
    url: "/last_modified_timestamps"
    object: last_modified_timestamps
    is_singleton: true
    actions:
      - list
  effective_settings:
    url: "/effective_settings"
    object: effective_settings
    is_singleton: true
    actions:
      - list
    filters:
      user_id: integer
      modified_before: datetime
      modified_since: datetime
  geolocations:
    url: "/geolocations"
    object: geolocation
    actions:
      - list
      - add
    filters:
      ids: integer[]
      modified_before: datetime
      modified_since: datetime
      user_ids: integer[]
      group_ids: integer[]
      per_page: integer
      page: integer
  custom_field_items:
    url: "/customfielditems"
    object: custom_field_item
    actions:
      - list
      - add
      - edit
    filters:
      customfield_id: integer
      ids: integer[]
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  custom_fields:
    url: "/customfields"
    object: custom_field
    actions:
      - list
    filters:
      ids: integer[]
      applies_to: string
      value_type: string
      modified_before: string
      modified_since: string
      per_page: integer
      page: integer
  jobcodes:
    url: "/jobcodes"
    object: jobcode
    actions:
      - list
      - add
      - edit
    filters:
      ids: integer[]
      parent_ids: integer[]
      type: string
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  jobcode_assignments:
    url: "/jobcode_assignments"
    object: jobcode_assignment
    actions:
      - list
      - add
      - delete
    filters:
      user_ids: integer[]
      type: string
      jobcode_parent_id: integer
      active: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  timesheets_deleted:
    url: "/timesheets_deleted"
    object: timesheet_deleted
    actions:
      - list
    filters:
      start_date: date
      end_date: date
      ids: integer[]
      modified_since: datetime
      modified_before: datetime
      group_ids: string
      user_ids: integer[]
      username: string
      jobcode_ids: integer[]
      jobcode_type: string
      type: string
      order_results_by: string
      order_results_reverse: boolean
      page: integer
      per_page: integer
  timesheets:
    url: "/timesheets"
    object: timesheet
    actions:
      - list
      - add
      - edit
      - delete
    filters:
      ids: integer[]
      start_date: date
      end_date: date
      jobcode_ids: integer[]
      user_ids: integer[]
      group_ids: integer[]
      on_the_clock: boolean
      jobcode_type: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  users:
    url: "/users"
    object: user
    actions:
      - list
      - add
      - edit
    filters:
      ids: integer[]
      usernames: string[]
      active: boolean
      first_name: string
      last_name: string
      modified_before: datetime
      modified_since: datetime
      per_page: integer
      page: integer
  current_user:
    url: "/current_user"
    object: user
    actions:
      - list
